### ISSUE TITLE
Parse terraform version -json output

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-exec#13]
From 0.13 onwards, `terraform version` accepts a `-json` flag. See https://github.com/hashicorp/terraform/pull/25252.

It might be worth trying `terraform version -json` first, before falling back to the legacy version output parsing logic added in #7.

**Comment by radeksimko** [comment]
This may become more important with https://github.com/hashicorp/terraform/pull/26975 where the static output is changing again.
