### ISSUE TITLE
Reflect new validation JSON output options

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-exec#141]
Investigate to see what is changing in https://github.com/hashicorp/terraform/pull/28057 and reflect it in the `Validate` method, which in proxy probably means reflecting the changes in `terraform-json`.

**Comment by alisdair** [comment]
Hi! I'm happy to chat about this change, so if you have any questions after investigating please reach out 😄

**Comment by radeksimko** [comment]
Addressed by #143
