### ISSUE TITLE
verifySumsSignature returns unexpected error: openpgp: signature made by unknown entity

### ISSUE THREAD

**Issue by frouioui** [hashicorp/terraform-exec#169]
## Description

Since Terraform release `0.15.1` and their GPG key rotation (https://github.com/hashicorp/terraform/pull/28505) I get the following error when running `tfinstall.Find` using the documentation's code and my own code:

```
unexpected error: openpgp: signature made by unknown entity
```

This error is generated by the following chunk of code. https://github.com/hashicorp/terraform-exec/blob/c4b847587f0455a3d3174740c83d7466ab7ab775/tfinstall/download.go#L98-L100

The checksum URLs I have during the execution are:

variable | value
--- | ---
sumsURL|`https://releases.hashicorp.com/terraform/0.15.1/terraform_0.15.1_SHA256SUMS`
sumsSigURL|`https://releases.hashicorp.com/terraform/0.15.1/terraform_0.15.1_SHA256SUMS.sig`

## Specs

Running on MacOS with go1.16.

**Comment by radeksimko** [comment]
Hi @frouioui 
Can you please confirm that you are on the latest `terraform-exec` version which contains the new pubkey? Specifically [0.13.3](https://github.com/hashicorp/terraform-exec/blob/main/CHANGELOG.md#0133-april-23-2021)

All other old versions are most likely going to fail installation because they have the old (now revoked) key embedded.

**Comment by frouioui** [comment]
Hello! Thank you, upgrading `terraform-exec` from `v0.13.0` to `v0.13.3` solved my issue.

**Comment by Castaglia** [comment]
Why was this done?  It breaks all older Terraform version installations, forcing upgrades (which are often non-trivial) that didn't need to happen.

**Comment by radeksimko** [comment]
@Castaglia You can read more about the security incident, which should explain _why_ here:
https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512/2

(it is also linked from the Changelog)
