### ISSUE TITLE
lock-timeout option not available as of Terraform 0.15

### ISSUE THREAD

**Issue by vfiftyfive** [hashicorp/terraform-exec#174]
Hi there,

In the README example, we have this line:
`err = tf.Init(context.Background(), tfexec.Upgrade(true), tfexec.LockTimeout("60s"))`

However, when running code similar to the example, I'm getting the following error message:

> Expected no error, but got: -lock, -lock-timeout, -verify-plugins, and -get-plugins options are no longer available as of Terraform 0.15: unexpected version 0.15.3 (min: -, max: 0.15.0)

If I remove the timeout option, it is working fine.
You may want to correct the example or add explanations on how to install a particular version of Terraform?

Cheers

Nic

**Comment by radeksimko** [comment]
Hi @vfiftyfive 
Where do you see that outdated example?

That option was removed from there 25 days ago in https://github.com/hashicorp/terraform-exec/commit/24faa0c61b0bf1f5ca719453863ca54a23eda621

**Comment by vfiftyfive** [comment]
Oh didn't see that one. Was using an older version of the README example. Makes sense now!
Thanks for the clarification.

Nic
