### ISSUE TITLE
Plan/apply `-replace` and `-refresh=false` options are missing

### ISSUE THREAD

**Issue by thrashr888** [hashicorp/terraform-exec#184]
There's a couple of new plan features that could use support added to this lib:
https://www.terraform.io/docs/cli/commands/plan.html#planning-options

**Comment by radeksimko** [comment]
`refresh` option is already supported for both apply and plan command:

https://github.com/hashicorp/terraform-exec/blob/7fa6ba66697a5ca8b7fda210a2fcc13fdbcb5ba1/tfexec/apply.go#L72-L74

https://github.com/hashicorp/terraform-exec/blob/7fa6ba66697a5ca8b7fda210a2fcc13fdbcb5ba1/tfexec/plan.go#L62-L64

I just raised #211 to add the missing `replace` argument/option.
