### ISSUE TITLE
Support error wrapping for locked state errors

### ISSUE THREAD

**Issue by alec-rabold** [hashicorp/terraform-exec#222]
First off thank you for maintaining this project! It's such a great tool for automating TF workflows in code.

**Feature**

One addition that I believe would be helpful is a first-class error when there's an issue acquiring a state lock, as well as the `LockInfo` so that a `force-unlock` is possible if appropriate. The driving use-case for us is when the Terraform process unexpectedly exits early, requiring either manual intervention or a separate `stderr` logger to catch this.

I've created a pull request (https://github.com/hashicorp/terraform-exec/pull/221) and was hoping to get some thoughts from you all.

Thanks!

**Comment by radeksimko** [comment]
#221 was just merged
