### ISSUE TITLE
Issue of terraform init

### ISSUE THREAD

**Issue by zjkyz8** [hashicorp/terraform-exec#263]
Hi guys
there is a mismatch for doc and implement about terraform init funciton, code like below:
![image](https://user-images.githubusercontent.com/1856389/147427311-d7f6d421-48b5-46b6-9ea1-6e0318403964.png)
 
Doc means param of execPath can be blank, but code means not.

Does this need to fix?
Thanks

**Comment by radeksimko** [comment]
Thanks for the note, this was already addressed in https://github.com/hashicorp/terraform-exec/pull/243 and will be part of the upcoming release.
