### ISSUE TITLE
go mod tidy have error：but does not contain package github.com/hashicorp/terraform-exec/tfinstall

### ISSUE THREAD

**Issue by LZiHaN** [hashicorp/terraform-exec#311]
While writing the provider, I got the following error for go mod tidy.
`terraform-provider-qingcloudkube/qingcloudkube tested by
        terraform-provider-qingcloudkube/qingcloudkube.test imports
        github.com/hashicorp/terraform-plugin-sdk/helper/resource imports
        github.com/hashicorp/terraform-plugin-test/v2 imports
        github.com/hashicorp/terraform-exec/tfinstall: module github.com/hashicorp/terraform-exec@latest found (v0.16.1), but does not contain package github.com/hashicorp/terraform-exec/tfinstall`

**Comment by kmoe** [comment]
The package `github.com/hashicorp/terraform-exec/tfinstall` no longer exists as of version 0.16.0 of this module.

It looks like you may be using an old version of `github.com/hashicorp/terraform-plugin-sdk` that depends on `github.com/hashicorp/terraform-plugin-test/v2`, which is no longer used and was incorporated into `terraform-plugin-sdk` as an internal package.

Is it possible for you to upgrade to v2 of `terraform-plugin-sdk`? Please see the following guide: https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide#version-2-of-the-module

**Comment by kmoe** [comment]
Since this doesn't look like a bug or enhancement request, I'm going to close this issue. @LZiHaN, please reopen if you believe there is a bug here. Alternatively you can find more help for provider development at the official forum: https://discuss.hashicorp.com/c/terraform-providers/31.
