### ISSUE TITLE
Any thoughts on doing FS ops through afero or a custom FS interface? 

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform-exec#317]
I'm looking to use this module but it has been difficult to test our own functions because terraform-exec does not use an FS interface. Any thoughts on doing operations through any sort of FS interface? maybe using afero or a custom interface?

**Comment by radeksimko** [comment]
Hi @c4milo 
We have been thinking about some use cases where providing a virtual FS of some kind, as opposed to relying on OS FS, in the Editor Experience team. e.g. to run `terraform validate` prior to saving a file in the editor.

I'm curious though what is _your_ intended use case for this?

`terraform-exec` is nothing more than a wrapper around Terraform CLI, which means that Terraform itself would first need to provide some support for this as nearly all commands are pretty much hard-coded to read files from OS FS. The only exception I can think of is `terraform fmt`, which accepts file content via STDIN (`-`).

**Comment by c4milo** [comment]
> terraform-exec is nothing more than a wrapper around Terraform CLI, which means that Terraform itself would first need to provide some support for this as nearly all commands are pretty much hard-coded to read files from OS FS. The only exception I can think of is terraform fmt, which accepts file content via STDIN (-).

@radeksimko, that makes sense. 

> I'm curious though what is your intended use case for this?

I think the original ask doesn't make sense anymore. I will close for now. Thanks for such a quick response.
