### ISSUE TITLE
follow terraform apply

### ISSUE THREAD

**Issue by rdalbuquerque** [hashicorp/terraform-exec#344]
Hello folks,

I'm new to Go and trying to figure out both the perks of the language and terraform-exec.
I'm able to run `apply` successfully but can't figure out how to follow apply logs, like with the CLI.
Is it possible?

Thanks in advance!

**Comment by MusicDin** [comment]
Hi,

you can set output and error writers for tf command. For example:

```go
tf, err := tfexec.NewTerraform(workingDir, execPath)

if err != nil {
      // ...
}

tf.SetStdout(os.Stdout)
tf.SetStderr(os.Stderr)
```

**Comment by rdalbuquerque** [comment]
Sorry for the delay in the response, it worked, thanks!

**Comment by radeksimko** [comment]
Assumed that's resolved, I'm going to close this issue.

**Comment by shazib-summar** [comment]
hey @rdalbuquerque can you help me with the apply command? I cannot figure out how to pass variables to the apply command. The [tfexec.ApplyOption](https://pkg.go.dev/github.com/hashicorp/terraform-exec@v0.18.1/tfexec#ApplyOption) is an interface not a struct. How do I supply variables?

**Comment by shazib-summar** [comment]
For future wanderers, I figured it out. You are supposed to use `tfexec.Var()` to obtain a `tfexec.VarOption` object. This struct `tfexec.VarOption` implements the `ApplyOption` interface.

**Comment by shazib-summar** [comment]
hey @AdminTurnedDevOps its been a while since i posted this and since then i havent touched terraform. But following is what i could come up with right now

```golang

package main

import (
	"context"
	"log"

	"github.com/hashicorp/terraform-exec/tfexec"
)

func main() {

	tf, err := tfexec.NewTerraform("", "") // fill this in
	if err != nil {
		log.Fatalf("error: %s", err)
	}

	foo := tfexec.Var("identifier=value")

	err = tf.Apply(context.Background(), foo)
	if err != nil {
		log.Fatalf("error: %s", err)
	}
}

```
hope this helps...

[ref](https://pkg.go.dev/github.com/hashicorp/terraform-exec@v0.20.0/tfexec#Var) and [ref](https://github.com/hashicorp/terraform-exec/blob/e26205510919b4f893bb1370e000835b5d16ae4d/tfexec/destroy.go#L28)
