### ISSUE TITLE
Add functions that run Terraform commands with `-json` flag 

### ISSUE THREAD

**Issue by bendbennett** [hashicorp/terraform-exec#353]
### Use Case

There are a number of instances in which it would be useful to execute Terraform commands (e.g., _terraform apply_) with the `-json` flag. For instance, in order to be able to robustly [identify warnings](https://github.com/hashicorp/terraform-plugin-testing/issues/16) that have been emitted during the execution of a Terraform command, it would be useful to be able to capture the JSON output from the command and subsequently parse and interrogate it. 

### Proposal

Add the following functions to _terraform exec_:

- `ApplyJSON(ctx context.Context, w io.Writer, opts ...ApplyOption) error`
- `PlanJSON(ctx context.Context, w io.Writer, opts ...PlanOption) (bool, error)`
- `RefreshJSON(ctx context.Context, w io.Writer, opts ...RefreshCmdOption) error`
- `DestroyJSON(ctx context.Context, w io.Writer, opts ...DestroyOption) error`

Note that ` Validate(ctx context.Context) (*tfjson.ValidateOutput, error)` is already running _terraform refresh_  with the `-json` flag

**Comment by bflad** [comment]
Related: https://github.com/hashicorp/terraform-exec/issues/183
