### ISSUE TITLE
Support passing User-Agent

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-exec#9]
Tools executing Terraform (such as Terraform Language Server) would benefit from measuring impact/usage and one way of doing it would be by appending an identifier to User-Agent by passing `TF_APPEND_USER_AGENT` which then enables filtering data from whatever upstream backend requests were sent to.

https://github.com/hashicorp/terraform-plugin-test/issues/22

I'm not sure if this should be a first-class config option, but I'm creating this issue to discuss _whether_ it should.

**Comment by paultyng** [comment]
I think this should be a first class option. We should probably just add a default value to the User-Agent with `terraform-exec/v1.2.3` and append additionally to that if any value passed in the env var or manually (so 3 sources for the env var when passed down to the `exec.Cmd`: constant value of terraform-exec, code supplied value via `UserAgent` option function, and variable already specified in `os.Environ` (similar to checkpoint handling somewhat, although this should just append all 3).

**Comment by paultyng** [comment]
May need to use #22 to get the version info.
